// Copyright 2020-2021 The Khronos Group Inc.
//
// SPDX-License-Identifier: Apache-2.0

= Contributing

Contributions to the VK-GL-CTS-Tools repository are welcome.

Contributions may be in the form of Issues proposing a change, or Pull
Requests containing fixes for, or additions to the tools.

Please keep contributions focused on solving a single issue or bug.

== Copyright Notice and License Template

If you are adding a new file, it must be under the Apache 2.0 license, and
include the SPDX License Identifier following the copyright statement.

== Contributor License Agreement

When you propose a pull request on this repository you must execute the
Khronos Contributor License Agreement, to confirm you own your work and are
granting Khronos the necessary permissions to redistribute it under our
licenses.

=== AI-Assisted Contributions

By submitting a Contribution to this repository, you additionally represent
that, to the extent any of Your Contributions were developed with the
assistance of artificial intelligence tools or AI-generated code, You have
exercised sufficient review, judgment, and creative direction over such tools
and resulting material to reasonably consider it Your original creation, and
You are not aware of any third-party license, intellectual property claim, or
other restriction arising from such use that is associated with any part of
Your Contribution or use thereof.
